language: python

python:
  - "3.5.2"
  
install:
  - pip3 install -r requirements.txt
  - pip install coveralls
  - pip3 install redis

script:
  - service redis-server start
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test
  - coverage run --source=./ manage.py test
  
after_success:
  - coveralls
